// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DataImport.OldData
{
    public partial class Accounts
    {
        public Accounts()
        {
            Transactions = new HashSet<Transactions>();
        }

        public int AccountId { get; set; }
        public string VcAccount { get; set; }
        public bool? BlnActive { get; set; }

        public virtual ICollection<Transactions> Transactions { get; set; }
    }
}