// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DataImport.OldData
{
    public partial class AppErrors
    {
        public int ErrId { get; set; }
        public string ErrorMsg { get; set; }
        public string AppMethod { get; set; }
        public DateTime ErrDate { get; set; }
    }
}