// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DataImport.OldData
{
    public partial class Payees
    {
        public Payees()
        {
            Transactions = new HashSet<Transactions>();
        }

        public int PayeeId { get; set; }
        public string VcPayee { get; set; }
        public string VcAddress { get; set; }
        public bool? BlnActive { get; set; }

        public virtual ICollection<Transactions> Transactions { get; set; }
    }
}