// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DataImport.OldData
{
    public partial class Transactions
    {
        public int TransId { get; set; }
        public DateTime TransDate { get; set; }
        public string CheckNum { get; set; }
        public int? PayeeId { get; set; }
        public int? AccountId { get; set; }
        public string Memo { get; set; }
        public bool? Payment { get; set; }
        public bool? Deposit { get; set; }
        public decimal? TransAmount { get; set; }
        public decimal? EndBalance { get; set; }
        public decimal? BeginBalance { get; set; }

        public virtual Accounts Account { get; set; }
        public virtual Payees Payee { get; set; }
    }
}